### ISSUE TITLE
Prompt is triggered outside of new notes

### ISSUE THREAD

**Issue by hkcomori** [numeroflip/obsidian-auto-template-prompt#4]
Thank you for the useful plugin.

I found the following issue:

1. Select the text of Note A and execute "Extract current selection..." of Note composer (core plugin).
2. A new note is created with the contents of the selected text.
3. A link to that note is added at the caret position of Note A.
4. A prompt is triggerd at Note A.
5. When you select a template in the prompt, it will be inserted into Note A instead of a new note.

This is an example of how this issue can occur and it may happen in other ways as well.
I expect one of the following behaviors.:

- If a new note is detected, activate that note before triggering the prompt.
- Do not trigger the prompt if the new note is not active.

**Comment by numeroflip** [comment]
@hkcomori Thanks for the feedback and kudos for the detailed steps :) 
I wasn't really familiar with this feature to be honest :D  

I just published `v1.0.5`  which intends to fix it.
Can you confirm if it fixed the mentioned issue?

**Comment by hkcomori** [comment]
@numeroflip Thank you! This issue has been resolved.

However, unfortunately it has regressed.
In the following cases, the prompt should be triggered but it no longer is:

- Created a new note with "Create new note" command
- Clicked on a link to a non-existent note and created a new note
- Specified a non-existent note in Quick switcher (core plugin) and created a new note

It appears that the trigger check is being performed between when the new note is created and when it becomes active. 
I have some ideas. Could any of these be implemented?

- Perform a trigger check after a certain amount of time has passed with a timer once note creation is detected (simple but may not be stable)
- Perform a trigger check at the timing when an active note changes after detecting note creation

**Comment by jbaughman42** [comment]
I can confirm that prompts are not triggered under these cases:
- Created a new note with "Create new note" command
- Clicked on a link to a non-existent note and created a new note

**Comment by numeroflip** [comment]
Ugg... Sorry guys I should have tested it properly. 
For now I just reverted the previous changes in `1.0.6`, so it generally works, but the problem mentioned in this issue is still there.  

Might need to use a different approach to solve this. 
 Using a timer, @hkcomori  would defeinitely work in most cases. but It looks more like a hack, than a proper solution.

The general idea of 
> Perform a trigger check at the timing when an active note changes 

sounds promising though, ( thanks :) ) depending on the API Obsidian provides for such checks/events 

Will take a look.

**Comment by numeroflip** [comment]
I did some changes again, in version `1.1.0`

Did exactly that (was simpler than I anticipated) : 
> Perform a trigger check at the timing when an active note changes 


Now the issue with the "Extract current selection" command should be solved too

Would you kindly check/confirm that?

**Comment by hkcomori** [comment]
@numeroflip Awesome, it seems to be working perfectly.
Thanks for your fast work.
